<?php

namespace Miny;

require_once dirname(__FILE__) . '/../Extendable.php';

class FooPlugin
{

    public function bar()
    {
        return 'bar';
    }

    public function baz()
    {
        return 'baz';
    }

    public function foobar()
    {
        return 'foobar';
    }
}

/**
 * Test class for Extendable.
 * Generated by PHPUnit on 2012-08-05 at 11:01:55.
 */
class ExtendableTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Extendable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $object = new Extendable;
        $object->addMethod('foo', function() {
            return 'foo';
        });

        $object->addMethods(new FooPlugin, array(
            'bar', 'baz'
        ));

        $this->object = $object;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function test__call()
    {
        $this->assertEquals('foo', $this->object->foo());
        $this->assertEquals('bar', $this->object->bar());
        $this->assertEquals('baz', $this->object->baz());
        try {
            $this->object->foobar();
            $this->fail('Failed: should throw an exception.');
        } catch (\BadMethodCallException $e) {

        }
    }
}

?>
