<?php

namespace Miny\Routing;

require_once dirname(__FILE__) . '/../../Routing/Route.php';
require_once dirname(__FILE__) . '/../../Routing/Match.php';

/**
 * Test class for Match.
 * Generated by PHPUnit on 2012-08-02 at 23:46:36.
 */
class MatchTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Match
     */
    protected $object;
    protected $route;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->route = new Route('', NULL, array('foo' => 'bar', 'baz' => 'foobar'));
        $this->object = new Match($this->route, array('foo' => 'bar_baz'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Miny\Routing\Match::getParameters
     */
    public function testGetParameters()
    {
        $this->assertEquals(array('foo' => 'bar', 'baz' => 'foobar'), $this->object->getParameters());
    }

    /**
     * @covers Miny\Routing\Match::getRoute
     */
    public function testGetRoute()
    {
        $this->assertSame($this->route, $this->object->getRoute());
    }

}

?>
