<?php

namespace Miny\Factory;

require_once dirname(__FILE__) . '/../../Factory/Blueprint.php';

/**
 * Test class for ObjectDescriptor.
 * Generated by PHPUnit on 2012-08-02 at 23:43:56.
 */
class BlueprintTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ObjectDescriptor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Blueprint('SomeClass');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Miny\Factory\ObjectDescriptor::setArguments
     * @covers Miny\Factory\ObjectDescriptor::getArguments
     * @todo Implement testSetArguments().
     */
    public function testArguments()
    {
        $this->object->setArguments('a', 'b', 'c');
        $this->assertEquals($this->object->getArguments(), array('a', 'b', 'c'));
    }

    /**
     * @covers Miny\Factory\ObjectDescriptor::setParent
     * @covers Miny\Factory\ObjectDescriptor::hasParent
     * @covers Miny\Factory\ObjectDescriptor::getParent
     * @todo Implement testSetParent().
     */
    public function testParent()
    {
        $this->assertFalse($this->object->hasParent());
        $this->object->setParent('parent');
        $this->assertTrue($this->object->hasParent());
        $this->assertEquals($this->object->getParent(), 'parent');
    }

    /**
     * @covers Miny\Factory\ObjectDescriptor::addMethodCall
     * @covers Miny\Factory\ObjectDescriptor::getMethodCalls
     * @todo Implement testAddMethodCall().
     */
    public function testMethodCalls()
    {
        $this->object->addMethodCall('method_a', 'arg_1', 'arg_2');
        $this->object->addMethodCall('method_b', 'arg_1');
        $this->assertEquals(array(
            array('method_a', array('arg_1', 'arg_2')),
            array('method_b', array('arg_1'))
                ), $this->object->getMethodCalls());
    }

    /**
     * @covers Miny\Factory\ObjectDescriptor::setProperty
     * @covers Miny\Factory\ObjectDescriptor::getProperties
     * @todo Implement testSetProperty().
     */
    public function testProperties()
    {
        $array = array(
            'property_a' => 'value_a',
            'property_b' => 'value_b',
        );
        foreach ($array as $key => $value) {
            $this->object->setProperty($key, $value);
        }
        $this->assertEquals($array, $this->object->getProperties());
    }

    /**
     * @covers Miny\Factory\ObjectDescriptor::getClassName
     */
    public function testGetClassName()
    {
        $this->assertEquals($this->object->getClassName(), 'SomeClass');
    }

    /**
     * @covers Miny\Factory\ObjectDescriptor::isSingleton
     */
    public function testIsSingleton()
    {
        $this->assertTrue($this->object->isSingleton());
        $object = new Blueprint('SomeClass', false);
        $this->assertFalse($object->isSingleton());
    }

}

?>
